'use strict';
// Seed content — editable from /master without touching code.
const t = () => Date.now();
module.exports = {
  showcase: [
    { id: 'sc01', title: 'Topographic Relief — Everglades', category: 'Architecture', material: 'PLA Matte', tech: 'FDM · 0.12mm', dims: '320 × 220 × 40 mm', hours: 31, description: 'A 1:50,000 terrain slab printed in six interlocking tiles from USGS elevation data. Hand-fitted, no visible seams.', image: '/assets/sc-terrain.svg', tags: ['terrain', 'multi-part', 'large format'], featured: true, active: true, order: 1, created: t() },
    { id: 'sc02', title: 'Drone Frame Mk.IV', category: 'Engineering', material: 'Nylon CF', tech: 'FDM · 0.2mm', dims: '210 × 210 × 38 mm', hours: 9, description: 'Carbon-fiber nylon quad frame. Stiff, light, and printed with reinforced arm roots. Fourth revision for a local racing team.', image: '/assets/sc-drone.svg', tags: ['functional', 'carbon nylon'], featured: true, active: true, order: 2, created: t() },
    { id: 'sc03', title: 'Gear Train Demonstrator', category: 'Mechanical', material: 'PETG', tech: 'FDM · 0.16mm', dims: '180 × 120 × 60 mm', hours: 14, description: 'Twelve-gear compound train with press-fit bronze bushings. Tolerances held at ±0.08 mm across the set.', image: '/assets/sc-gears.svg', tags: ['tolerances', 'moving parts'], featured: false, active: true, order: 3, created: t() },
    { id: 'sc04', title: 'Faceted Bust — Study 07', category: 'Art', material: 'Resin Grey', tech: 'SLA · 0.05mm', dims: '95 × 80 × 160 mm', hours: 11, description: 'Low-poly portrait study with razor edges. Post-cured and lightly sanded at facet joins only.', image: '/assets/sc-bust.svg', tags: ['resin', 'sculpture'], featured: true, active: true, order: 4, created: t() },
    { id: 'sc05', title: 'Signal Tower Model', category: 'Architecture', material: 'PLA Matte', tech: 'FDM · 0.1mm', dims: '60 × 60 × 410 mm', hours: 27, description: 'Scale model of a lattice communications mast. 1.2 mm struts, printed upright with tree supports.', image: '/assets/sc-tower.svg', tags: ['scale model', 'fine struts'], featured: false, active: true, order: 5, created: t() },
    { id: 'sc06', title: 'Enclosure — Sensor Node', category: 'Product', material: 'ABS', tech: 'FDM · 0.2mm', dims: '84 × 58 × 32 mm', hours: 3, description: 'Weatherproof IP54 housing with living hinges and heat-set brass inserts. Batch of 40 for a field deployment.', image: '/assets/sc-enclosure.svg', tags: ['batch', 'inserts'], featured: false, active: true, order: 6, created: t() },
    { id: 'sc07', title: 'Parametric Lamp Shade', category: 'Interior', material: 'PETG Translucent', tech: 'FDM · vase mode', dims: '240 × 240 × 300 mm', hours: 8, description: 'Single-wall spiral print with a twisted hexagonal profile. Casts a moving pattern when lit.', image: '/assets/sc-lamp.svg', tags: ['vase mode', 'lighting'], featured: true, active: true, order: 7, created: t() },
    { id: 'sc08', title: 'Prosthetic Grip Prototype', category: 'Medical', material: 'TPU 95A', tech: 'FDM · 0.2mm', dims: '110 × 70 × 45 mm', hours: 6, description: 'Flexible assistive grip, iterated across five fits with the client. Soft-touch TPU with a rigid PETG core.', image: '/assets/sc-grip.svg', tags: ['flexible', 'iteration'], featured: false, active: true, order: 8, created: t() }
  ],
  products: [
    { id: 'p01', name: 'Cable Comb Set', sku: 'LZ-CC-01', price: 12, category: 'Desk', material: 'PLA', description: 'Six graduated cable combs for clean desk routing. Snap-fit, reprintable in any colour.', image: '/assets/p-combs.svg', variants: [{ name: 'Black', delta: 0 }, { name: 'Bone White', delta: 0 }, { name: 'Signal Red', delta: 1 }], stock: 40, leadDays: 2, featured: true, active: true, order: 1, created: t() },
    { id: 'p02', name: 'Hex Planter — 120', sku: 'LZ-HP-120', price: 24, category: 'Home', material: 'PETG', description: 'Faceted hexagonal planter with hidden drainage tray. 120 mm across flats.', image: '/assets/p-planter.svg', variants: [{ name: 'Graphite', delta: 0 }, { name: 'Sand', delta: 0 }, { name: 'XL 160mm', delta: 12 }], stock: 18, leadDays: 3, featured: true, active: true, order: 2, created: t() },
    { id: 'p03', name: 'Phone Dock — Tilt', sku: 'LZ-PD-02', price: 19, category: 'Desk', material: 'PLA Matte', description: 'Adjustable-angle dock with cable channel. Fits any phone with or without case.', image: '/assets/p-dock.svg', variants: [{ name: 'Black', delta: 0 }, { name: 'Bone White', delta: 0 }], stock: 25, leadDays: 2, featured: false, active: true, order: 3, created: t() },
    { id: 'p04', name: 'Wall Mount — Headset', sku: 'LZ-WM-04', price: 14, category: 'Desk', material: 'PETG', description: 'Low-profile headset hook with adhesive or screw mounting. Holds 2 kg.', image: '/assets/p-hook.svg', variants: [{ name: 'Black', delta: 0 }], stock: 60, leadDays: 1, featured: false, active: true, order: 4, created: t() },
    { id: 'p05', name: 'Terrain Coaster ×4', sku: 'LZ-TC-04', price: 28, category: 'Home', material: 'PLA Matte', description: 'Four coasters with Florida coastline bathymetry. Cork-backed.', image: '/assets/p-coasters.svg', variants: [{ name: 'Graphite', delta: 0 }, { name: 'Bone White', delta: 0 }], stock: 12, leadDays: 3, featured: true, active: true, order: 5, created: t() },
    { id: 'p06', name: 'Modular Drawer — 2U', sku: 'LZ-MD-2U', price: 32, category: 'Workshop', material: 'PETG', description: 'Stackable parts drawer system. Two units high, dovetail-locked sides, labelled fronts.', image: '/assets/p-drawer.svg', variants: [{ name: 'Graphite', delta: 0 }, { name: '4U (double)', delta: 22 }], stock: 9, leadDays: 4, featured: false, active: true, order: 6, created: t() },
    { id: 'p07', name: 'Low-Poly Fox', sku: 'LZ-LF-01', price: 36, category: 'Art', material: 'Resin', description: 'Faceted resin sculpture, 140 mm tall. Sanded and matte-sealed.', image: '/assets/p-fox.svg', variants: [{ name: 'Grey', delta: 0 }, { name: 'Signal Red', delta: 4 }], stock: 6, leadDays: 5, featured: true, active: true, order: 7, created: t() },
    { id: 'p08', name: 'Key Organizer', sku: 'LZ-KO-01', price: 16, category: 'Everyday', material: 'Nylon', description: 'Folding key organizer for up to 8 keys. Stainless hardware included.', image: '/assets/p-keys.svg', variants: [{ name: 'Black', delta: 0 }], stock: 30, leadDays: 2, featured: false, active: true, order: 8, created: t() }
  ],
  reviews: [
    { id: 'r01', name: 'Marcus T.', location: 'Coral Springs, FL', rating: 5, text: 'Had a broken dishwasher rail part reverse-engineered and printed in two days. Fits better than the original.', service: 'Custom part', active: true, order: 1, created: t() },
    { id: 'r02', name: 'Dana R.', location: 'Boca Raton, FL', rating: 5, text: 'The terrain model for our office lobby was stunning. Tiles lined up perfectly and delivery was on time.', service: 'Architecture model', active: true, order: 2, created: t() },
    { id: 'r03', name: 'Kevin O.', location: 'Orlando, FL', rating: 4, text: 'Ordered 40 enclosures for a field project. Consistent quality across the whole batch. Shipping to Orlando took two days.', service: 'Batch production', active: true, order: 3, created: t() },
    { id: 'r04', name: 'Priya S.', location: 'Margate, FL', rating: 5, text: 'Walked in with a sketch, walked out a week later with a working prototype. Great communication throughout.', service: 'Prototype', active: true, order: 4, created: t() },
    { id: 'r05', name: 'Luis F.', location: 'Atlanta, GA', rating: 5, text: 'Resin figure quality is exceptional. Packaged like a piece of jewellery, arrived flawless.', service: 'Store order', active: true, order: 5, created: t() }
  ]
};
