'use strict';
/* End-to-end API smoke test. Run with the server up: node tools/smoke.js */
const B = 'http://localhost:3000'; let cookie = '';
const j = async (u, o = {}) => { const r = await fetch(B + u, Object.assign({ headers: { 'Content-Type': 'application/json', cookie } }, o)); const sc = r.headers.get('set-cookie'); if (sc) cookie = sc.split(';')[0]; const t = await r.text(); let d; try { d = JSON.parse(t); } catch { d = t.slice(0, 80); } return { s: r.status, d }; };
let fails = 0;
const ok = (n, c, extra = '') => { if (!c) fails++; console.log((c ? 'PASS ' : 'FAIL ') + n + (extra ? ' -> ' + extra : '')); };
(async () => {
  let r = await j('/api/content'); ok('content', r.s === 200 && r.d.products.length >= 8 && r.d.showcase.length >= 8 && r.d.reviews.length >= 5);
  // 33063 was a pickup ZIP; with delivery only it is priced as local courier
  r = await j('/api/delivery/33063'); ok('zone local (former pickup ZIP)', r.d.zone === 'local' && r.d.rate === 9, JSON.stringify(r.d));
  r = await j('/api/delivery/33131'); ok('zone local', r.d.zone === 'local');
  r = await j('/api/delivery/32801'); ok('zone florida', r.d.zone === 'florida');
  r = await j('/api/delivery/30301'); ok('zone national', r.d.zone === 'national');
  r = await j('/api/delivery/abc'); ok('zone unknown', r.d.zone === 'unknown');
  r = await j('/api/cart/totals', { method: 'POST', body: JSON.stringify({ items: [{ id: 'p02', qty: 2, variant: 'XL 160mm' }, { id: 'p07', qty: 1 }], zip: '30301', method: 'delivery', express: true }) });
  ok('totals', r.d.subtotal === 108 && r.d.shipping === 47 && r.d.zone === 'national', JSON.stringify(r.d));
  r = await j('/api/cart/totals', { method: 'POST', body: JSON.stringify({ items: [{ id: 'p07', qty: 5 }], zip: '32801', method: 'delivery' }) });
  ok('free shipping over 150', r.d.shipping === 0 && r.d.subtotal === 180, JSON.stringify(r.d));
  r = await j('/api/orders', { method: 'POST', body: JSON.stringify({ items: [{ id: 'p01', qty: 1, variant: 'Signal Red' }, { id: 'p05', qty: 1 }], method: 'delivery', express: false, sid: 'test-sid', customer: { name: 'Test Buyer', email: 'buyer@example.com', address: '1 Palm Ave', city: 'Orlando', zip: '32801' } }) });
  ok('order create', r.s === 200 && r.d.order.id.startsWith('LZ-'), r.d.order && r.d.order.id + ' ' + r.d.order.totals.total); const oid = r.d.order && r.d.order.id;
  r = await j('/api/orders', { method: 'POST', body: JSON.stringify({ items: [{ id: 'p02', qty: 1 }], sid: 'test-sid2', customer: { name: 'No Address', email: 'noaddr@example.com' } }) });
  ok('order without an address rejected', r.s === 400, JSON.stringify(r.d));
  r = await j('/api/orders', { method: 'POST', body: JSON.stringify({ items: [], customer: { name: 'x', email: 'y', address: '1 A St', zip: '33063' } }) }); ok('order empty rejected', r.s === 400);
  r = await j('/api/orders/' + oid); ok('order lookup', r.s === 200 && r.d.status === 'new');
  r = await j('/api/quotes/estimate', { method: 'POST', body: JSON.stringify({ material: 'petg', infill: 30, qty: 3, volumeCm3: 45, finish: 'sanded' }) }); ok('estimate', r.d.total > 15, JSON.stringify(r.d));
  const stl = Buffer.alloc(84 + 50 * 12); stl.writeUInt32LE(12, 80); // 12-triangle 10mm cube
  const V = [[0, 0, 0], [10, 0, 0], [10, 10, 0], [0, 10, 0], [0, 0, 10], [10, 0, 10], [10, 10, 10], [0, 10, 10]];
  const F = [[0, 2, 1], [0, 3, 2], [4, 5, 6], [4, 6, 7], [0, 1, 5], [0, 5, 4], [1, 2, 6], [1, 6, 5], [2, 3, 7], [2, 7, 6], [3, 0, 4], [3, 4, 7]];
  F.forEach((f, i) => { const o = 84 + i * 50 + 12; f.forEach((vi, k) => V[vi].forEach((c, a) => stl.writeFloatLE(c, o + k * 12 + a * 4))); });
  require('fs').writeFileSync(require('path').join(__dirname, 'cube.stl'), stl);
  r = await j('/api/quotes', { method: 'POST', body: JSON.stringify({ name: 'Quote Tester', email: 'q@example.com', material: 'pla', infill: 20, qty: 1, volumeCm3: 1, notes: 'cube test', fileName: 'cube.stl', fileData: 'data:model/stl;base64,' + stl.toString('base64'), sid: 'test-sid' }) });
  ok('quote create + file', r.s === 200 && r.d.quote.file, r.d.quote && r.d.quote.id);
  r = await j('/api/messages', { method: 'POST', body: JSON.stringify({ name: 'Msg', email: 'm@example.com', message: 'Can you print carbon fiber?' }) }); ok('message', r.s === 200);
  for (const t of ['pageview', 'click', 'product_view', 'add_to_cart', 'checkout_start']) await j('/api/track', { method: 'POST', body: JSON.stringify({ type: t, page: '/store', label: 'smoke:' + t, sid: 'test-sid' }) });
  r = await j('/api/admin/stats/30'); ok('admin blocked', r.s === 401);
  r = await j('/api/admin/login', { method: 'POST', body: JSON.stringify({ password: 'wrong' }) }); ok('bad login', r.s === 401);
  r = await j('/api/admin/login', { method: 'POST', body: JSON.stringify({ password: process.env.LZ_PW || 'layerzero' }) }); ok('login', r.s === 200 && cookie.includes('lz_admin'));
  r = await j('/api/admin/stats/30'); ok('stats', r.s === 200 && r.d.funnel.orders >= 2 && r.d.revenue > 0, `sessions ${r.d.sessions} orders ${r.d.funnel.orders} rev ${r.d.revenue} conv ${r.d.conversion}%`);
  r = await j('/api/admin/products', { method: 'POST', body: JSON.stringify({ name: 'Smoke Test Product', sku: 'LZ-TEST', price: 9.5, category: 'Test', material: 'PLA', stock: 3, leadDays: 1, image: '/assets/p-keys.svg', variants: [{ name: 'A', delta: 0 }] }) }); ok('product create', r.s === 200, r.d.item && r.d.item.id); const pid = r.d.item && r.d.item.id;
  r = await j('/api/content'); ok('product visible', r.d.products.some(p => p.id === pid));
  r = await j('/api/admin/products', { method: 'POST', body: JSON.stringify({ id: pid, active: false }) }); r = await j('/api/content'); ok('product hidden', !r.d.products.some(p => p.id === pid));
  r = await j('/api/admin/products/' + pid, { method: 'DELETE' }); ok('product delete', r.s === 200);
  r = await j('/api/admin/orders/' + oid, { method: 'PATCH', body: JSON.stringify({ status: 'printing', adminNote: 'started' }) }); ok('order status', r.d.order && r.d.order.status === 'printing');
  r = await j('/api/admin/showcase/reorder', { method: 'POST', body: JSON.stringify({ ids: ['sc08', 'sc01'] }) }); r = await j('/api/content'); ok('reorder', r.d.showcase[0].id === 'sc08');
  await j('/api/admin/showcase/reorder', { method: 'POST', body: JSON.stringify({ ids: ['sc01', 'sc02', 'sc03', 'sc04', 'sc05', 'sc06', 'sc07', 'sc08'] }) });
  r = await j('/api/admin/upload', { method: 'POST', body: JSON.stringify({ data: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==' }) }); ok('upload', r.s === 200 && r.d.url.startsWith('/uploads/'));
  r = await j('/api/admin/settings', { method: 'PUT', body: JSON.stringify({ delivery: { rates: { local: 9, florida: 14, national: 22, expressSurcharge: 25, freeOver: 150 } } }) }); ok('settings save', r.s === 200);
  r = await j('/api/admin/settings'); ok('settings read', r.d.delivery.rates.local === 9 && !!r.d.business.name);
  r = await j('/api/admin/logout', { method: 'POST' }); r = await j('/api/admin/me'); ok('logout', r.d.admin === false);
  r = await j('/nope'); ok('404 page', r.s === 404);
  r = await j('/..%2fserver.js'); ok('traversal blocked', r.s !== 200 || typeof r.d !== 'string' || !r.d.includes('require'));
  console.log(fails ? `\n${fails} FAILED` : '\nALL PASSED');
})();
